Traceback (most recent call last):
  File "/home/munakala/miniconda3/envs/IOOS-test/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/munakala/miniconda3/envs/IOOS-test/lib/python3.9/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/munakala/miniconda3/envs/IOOS-test/lib/python3.9/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/munakala/miniconda3/envs/IOOS-test/lib/python3.9/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/home/munakala/miniconda3/envs/IOOS-test/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/munakala/miniconda3/envs/IOOS-test/lib/python3.9/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/home/munakala/miniconda3/envs/IOOS-test/lib/python3.9/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/munakala/miniconda3/envs/IOOS-test/lib/python3.9/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
try:
    from urllib.parse import unquote
except ImportError:
    from urllib2 import unquote


urlbase = "https://erddap.axiomdatascience.com/erddap/tabledap"

fname = "sensor_service.csvp"

columns = (
    "time",
    "value",
    "station",
    "longitude",
    "latitude",
    "parameter",
    "unit",
    "depth",
)
params = {
    # Inequalities do not exist in HTTP parameters,
    # so we need to hardcode the `>` in the time key to get a '>='.
    # Note that a '>' or '<' cannot be encoded with `urlencode`, only `>=` and `<=`.
    "time>": "2017-01-00T00:00:00Z",
    "station": '"urn:ioos:station:wmo:44011"',
    "parameter": '"Significant Wave Height"',
    "unit": '"m"',
}

url = encode_erddap(urlbase, fname, columns, params)

print(unquote(url))
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mHTTPError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-2-943d266f5ccf>[0m in [0;36m<module>[0;34m[0m
[1;32m     29[0m }
[1;32m     30[0m [0;34m[0m[0m
[0;32m---> 31[0;31m [0murl[0m [0;34m=[0m [0mencode_erddap[0m[0;34m([0m[0murlbase[0m[0;34m,[0m [0mfname[0m[0;34m,[0m [0mcolumns[0m[0;34m,[0m [0mparams[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     32[0m [0;34m[0m[0m
[1;32m     33[0m [0mprint[0m[0;34m([0m[0munquote[0m[0;34m([0m[0murl[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m<ipython-input-1-9ee591a73e2b>[0m in [0;36mencode_erddap[0;34m(urlbase, fname, columns, params)[0m
[1;32m     28[0m     [0murl[0m [0;34m=[0m [0mendpoint[0m[0;34m([0m[0murlbase[0m[0;34m=[0m[0murlbase[0m[0;34m,[0m [0mfname[0m[0;34m=[0m[0mfname[0m[0;34m,[0m [0mcolumns[0m[0;34m=[0m[0mcolumns[0m[0;34m,[0m [0mparams[0m[0;34m=[0m[0mparams[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     29[0m     [0mr[0m [0;34m=[0m [0mrequests[0m[0;34m.[0m[0mget[0m[0;34m([0m[0murl[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 30[0;31m     [0mr[0m[0;34m.[0m[0mraise_for_status[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     31[0m     [0;32mreturn[0m [0murl[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/miniconda3/envs/IOOS-test/lib/python3.9/site-packages/requests/models.py[0m in [0;36mraise_for_status[0;34m(self)[0m
[1;32m    941[0m [0;34m[0m[0m
[1;32m    942[0m         [0;32mif[0m [0mhttp_error_msg[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 943[0;31m             [0;32mraise[0m [0mHTTPError[0m[0;34m([0m[0mhttp_error_msg[0m[0;34m,[0m [0mresponse[0m[0;34m=[0m[0mself[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    944[0m [0;34m[0m[0m
[1;32m    945[0m     [0;32mdef[0m [0mclose[0m[0;34m([0m[0mself[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;31mHTTPError[0m: 404 Client Error:  for url: https://erddap.axiomdatascience.com/erddap/tabledap/sensor_service.csvp?time,value,station,longitude,latitude,parameter,unit,depth&time%3E=2017-01-00T00%3A00%3A00Z&station=%22urn%3Aioos%3Astation%3Awmo%3A44011%22&parameter=%22Significant+Wave+Height%22&unit=%22m%22
HTTPError: 404 Client Error:  for url: https://erddap.axiomdatascience.com/erddap/tabledap/sensor_service.csvp?time,value,station,longitude,latitude,parameter,unit,depth&time%3E=2017-01-00T00%3A00%3A00Z&station=%22urn%3Aioos%3Astation%3Awmo%3A44011%22&parameter=%22Significant+Wave+Height%22&unit=%22m%22

